name: Daily STRATZ Meta Screenshot

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.2-jammy   # Playwright image s Chromium
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Check secrets
        run: |
          echo "Has STRATZ_TOKEN? ${{ secrets.STRATZ_TOKEN != '' }}"
          echo "Has DISCORD_WEBHOOK_URL? ${{ secrets.DISCORD_WEBHOOK_URL != '' }}"

      - name: Run screenshot + send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          STRATZ_TOKEN: ${{ secrets.STRATZ_TOKEN }}
        run: node screenshot.js
